#include "source/configuration/system_constants.h"
#include "tools/neslib_famitracker/neslib.h"
#include "source/library/bank_helpers.h"
#include "source/map/map.h"

// This file is autogenerated, so it ends up in the `temp` directory.
#include "temp/level_overworld.h"

// Loads the map at the player's current position into the ram variable given. 
// Kept in a separate file, as this must remain in the primary bank so it can
// read data from another prg bank.
void load_map() {
    
    // Need to switch to the bank that stores this map data.
    bank_push(PRG_BANK_MAP_OVERWORLD);
    memcpy(currentMap, overworld + (playerOverworldPosition << 8), 256);
    bank_pop();

}