on: 
  push:
  # Run once a week to make sure nothing randomly breaks without us knowing
  schedule:
    - cron: '23 23 * * 0'

jobs:
  build_rom:
    runs-on: ubuntu-latest
    container: cppchriscpp/create-nes-game:v1.0.10
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Move things into the spots github CI expects them in
        run: "cp -a /root/. /github/home"
      - name: Install dependencies
        run: create-nes-game download-dependencies --assume-yes
      - name: Build the game
        run: create-nes-game build
      - name: Start xvfb 
        run: sudo Xvfb :99 -screen 0 1280x1024x24 &
      - name: Run unit tests
        run: DISPLAY=:99 create-nes-game test --debug
      - name: Clean up xvfb
        uses: bcomnes/cleanup-xvfb@v1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Game Download
          path: rom
      - name: Prep for s3
        run: |
          mkdir s3-rom && 
          cp rom/nes-starter-kit-example.nes s3-rom/starter.latest.nes && 
          cp rom/nes-starter-kit-example.dbg s3-rom/starter.latest.dbg && 
          cp rom/nes-starter-kit-example.nes s3-rom/starter.${{ github.run_number }}.nes &&
          cp rom/nes-starter-kit-example.dbg s3-rom/starter.${{ github.run_number }}.dbg
          
      - name: Copy artifacts into s3
        uses: shallwefootball/s3-upload-action@master
        with: 
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: nes-starter-kit
          source_dir: s3-rom
          destination_dir: ${{ github.ref_name }}
